### ISSUE TITLE
Unit test failing

### ISSUE THREAD

**Issue by jmlsf** [r0man/cljs-http#114]
@r0man The unit tests are failing as we discussed.  It appears to be because of phantomjs.  This fix looks a bit ugly.  See this issue:

https://github.com/bensu/doo/issues/140

I tried it with karma & chrome-headless and the tests pass.  I'll submit a PR if you want to try it out.

**Comment by r0man** [comment]
@jmlsf Yes, a PR would be welcome. We can also drop phantom if there are better options?

**Comment by jmlsf** [comment]
If we can get chrome-headless to work in travis, that is surely better.  The problem here is that I need to install karma to use chrome-headless with lein-doo.  I think I'll have to add a package.json to do so.
