### ISSUE TITLE
Struggling with CORS post request to compojure / ring backend using ring.core / cljs-http...

### ISSUE THREAD

**Issue by ckuttruff** [r0man/cljs-http#117]
Hey all, firstly, thanks for the project!  @r0man have also been working with `ring-cors` to try to get this sorted.  I have, however gotten hung up on some preflight issues on the cljs-https side.

Server code (uses compojure / ring / misc middleware):
https://github.com/ckuttruff/orghub/blob/master/src/orghub/server.clj#L36
Relevant section (sorry, started to throw the kitchen sink at these headers):
```clojure
(def app (-> app-routes
             (wrap-cors  :access-control-allow-origin [#"^(http(s)?://)?localhost:(\d){4}$"]
                         :access-control-allow-credentials true
                         :access-control-allow-methods [:get :post :options]
                         :access-control-allow-headers ["Content-Type" "Accept" "Cache-Control" "Origin" "User-Agent"])))
```

The following curl command works swimmingly:
```bash
$ curl -i  -d '{"email":"foo@gmail.com", "password":"foo"}' -H "Content-Type: application/json"  -X POST localhost:3000/loginHTTP/1.1 200 OK
Date: Sat, 19 May 2018 19:32:21 GMT
Content-Length: 0
Server: Jetty(9.2.21.v20170120)
```

But the following cljs-http call fails with `XHR failed loading: OPTIONS`:
https://github.com/ckuttruff/orghub/blob/master/src/orghub/components/login.cljs#L16
```clojure
  (go (let [response (<! (http/post "http://localhost:3000/login"
                                    {:json-params {:email email :password pw}
       
                                     }))]
        (prn response)
        (prn (:status response))
        (prn (map :login (:body response)))))
```

Thanks in advance for any insights you might be able to provide.  I'm sorry if I've missed something obvious, but I've been digging into CORS docs and am just having difficulty cause I'm not even spawning the preflight request and I'm not sure why the behavior would be different for the curl command (is that not triggering the same CORS request?)

Cheers!  Thanks again for your work on this and other cljs projects!

**Comment by ckuttruff** [comment]
ooohhh, the plot thickens... got more useful debug output from firefox than chrome:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/login. (Reason: expected ‘true’ in CORS header ‘Access-Control-Allow-Credentials’).`

gonna try setting that now

**Comment by ckuttruff** [comment]
lol, okay, so this change addressed one issue.  #FunWithTyping
https://github.com/ckuttruff/orghub/commit/6c3a51250a072f14b0d2a35827ccd5021848ea86

```diff
-                         :access-control-allow-credentials true
+                         :access-control-allow-credentials "true"
```

Incredibly this fixes things for firefox, but not for chrome.  So there's a secondary issue with headers here in terms of what chrome is sending and what the server is expecting at this point

**Comment by ckuttruff** [comment]
![headers](https://user-images.githubusercontent.com/253577/40272803-bf435554-5b68-11e8-9fc8-881836905445.png)

A side-by-side of the request headers.
Chrome (on the left) gets `XHR failed loading: POST "http://localhost:3000/login".`
Firefox (on the right) succeeds.

Obv some minor differences here.  Gonna dig into the CORS docs to see what's up here...

**Comment by ckuttruff** [comment]
p.s. to folks running `lein figwheel` alongside `lein ring server`:

The simplest thing for me was to set a handler on the clj side and unify the traffic under the same port (such that it won't trigger CORS (which has been a gigantic pain to try to figure out)).

Here's the commit that got things working for me:
https://github.com/ckuttruff/orghub/commit/190d4129057f93484104df97255e252e722dba9f

And there's a dead simple example of using the `ring-handler` option in figwheel here:
https://github.com/bhauman/lein-figwheel/tree/master/examples/using-ring-handler

No more futzing around between localhost:3000 and localhost:3449
More secure anyways and more like how production will be running.

I know this doesn't resolve the underlying XHR failure here, and best of luck to folks still in that fight, but this is a perfectly reasonable resolution for me :)  I will close, but if others still find a need to sort this out and resurrect, please do.

Thanks all.

**Comment by divs1210** [comment]
Hi @ckuttruff, I'm facing the same issue. Did you get around it? I can see you have switched your project over to Ruby - not a good sign, but thought I should ask anyway.

**Comment by ckuttruff** [comment]
@divs1210 sorry moved repo:
https://github.com/ckuttruff/orghub-clj/commit/190d4129057f93484104df97255e252e722dba9f

The code in should show my approach.  I believe I got this sorted but was dealing with other issues such that I wanted to simplify.

Would love to use clj / cljs, but yeah, started with ruby one and stripped out all the progressive web app stuff and a lot of the front-end complexity and offline ambitions. 

I def got over this CORS hurdle so lemme know if that commit of later code is unclear.  Gist is to run on same server to avoid CORS altogether.  Lol this is bringing back bad memories.  All this was a headache

**Comment by ckuttruff** [comment]
@divs1210 I updated stale links.  Hope it's helpful.  Good luck!
