### ISSUE TITLE
The custom channel seems doesn't work

### ISSUE THREAD

**Issue by kangbb** [r0man/cljs-http#123]
I hava tried it as following:
```clj
(def body (chan 1 (map :body)))
(go (while true
      (println (<! body))))
(go (http/get "https://api.github.com/users"
              {:with-credentials? false
               :query-params      {"since" 135}}
              {:channel body}))
```
But nothing will print.

**Comment by seancorfield** [comment]
@kangbb You're passing two maps -- it should just be one:
```clojure
(go (http/get "https://api.github.com/users"
              {:with-credentials? false
               :query-params      {"since" 135}
               :channel body}))
```

**Comment by kangbb** [comment]
> @kangbb You're passing two maps -- it should just be one:
> 
> ```clojure
> (go (http/get "https://api.github.com/users"
>               {:with-credentials? false
>                :query-params      {"since" 135}
>                :channel           body}))
> ```

Thanks a lot, it works.

**Comment by kiramclean** [comment]
@kangbb How are you consuming the responses from the custom channel? I'm running into the issue described in https://github.com/r0man/cljs-http/issues/66, but would like to use a custom channel.
