### ISSUE TITLE
jsonp throws exception due to goog.net.Jsonp api changes

### ISSUE THREAD

**Issue by vladkotu** [r0man/cljs-http#124]
Attempt to get data using `cljs-http.client/jsonp` throws an exception:
```
Uncaught TypeError: this.uri_.cloneWithParams is not a function
    at goog.net.Jsonp.send (jsonp.js:229)
    at Object.cljs_http$core$jsonp [as jsonp] (core.cljs:125)
```

Seems like it caused by these [changes](https://github.com/google/closure-library/commit/8d38b0b4cfbd1dc979a5b49ae12ea2e0478b01c9#diff-59a6d30efb3f36962c8b446fc7b196c8R61) 
In short - `goog.net.Jsonp` expect uri to be `goog.html.TrustedResourceUrl` (string of goog.Uri were valid before)

Potentially could be fixed by changing how url is build from request [here](https://github.com/r0man/cljs-http/blob/3bde7ab4f6ee320486dd6801d6d034b6ad360ba2/src/cljs_http/core.cljs#L122), something like this:

```clojure
;; ↓ new imports
[goog.html TrustedResourceUrl]
[goog.string Const]

(let [channel (async/chan)
      ;; ↓ trusted url insted of just url
      trusted-url (->> request
                       (util/build-url)
                       Const/from
                       TrustedResourceUrl/fromConstant)
      jsonp   (Jsonp. trusted-url callback-name)]
  (.....))
```

**Comment by vladkotu** [comment]
looks like it is reproducible only in my local env 
(`shadow-cljs` uses very latest version of `org.clojure/google-closure-library`)
hence closing this issue

**Comment by realgenekim** [comment]
Hi, @vladkotu — I'm having the same problem, using shadow-cljs.  Thanks for determining what is causing it.  How were you able to resolve the problem?  Many thanks!!!

**Comment by vladkotu** [comment]
Hi @realgenekim  All i needed was to call jsonp endpoint once a while. No other network interactions... so i just wrote custom jsonp function for myself. 
Setting google closure lib version explicitly in your project should help, however i'm not sure shadow-cljs will handle such downgrade smoothly. 
Anyway I would better post an issue in shadow-cljs project
