### ISSUE TITLE
Error "Uncaught Error: Undefined nameToPath for com.cognitect.transit.eq "

### ISSUE THREAD

**Issue by Gonzih** [r0man/cljs-http#29]
Hello, I was just trying to poke around with this library and lein figwheel without much success. I'm getting error "Uncaught Error: Undefined nameToPath for com.cognitect.transit.eq " which is coming from transit (probably). Clojurescript version is 0.0-2356. Also I see bunch of warnings during compilation:

```
WARNING: unsigned-bit-shift-right already refers to: #'clojure.core/unsigned-bit-shift-right in namespace: cljs.core, being replaced by: #'cljs.core/unsigned-bit-shift-right
WARNING: No such namespace: com.cognitect.transit.eq at line 15 file:/home/gnzh/.m2/repository/com/cognitect/transit-cljs/0.8.188/transit-cljs-0.8.188.jar!/cognitect/transit.cljs
WARNING: No such namespace: com.cognitect.transit.types at line 15 file:/home/gnzh/.m2/repository/com/cognitect/transit-cljs/0.8.188/transit-cljs-0.8.188.jar!/cognitect/transit.cljs
WARNING: No such namespace: com.cognitect.transit at line 15 file:/home/gnzh/.m2/repository/com/cognitect/transit-cljs/0.8.188/transit-cljs-0.8.188.jar!/cognitect/transit.cljs
```

Are there any limitations on which clojurescript version I can use with this library?

Thanks!

**Comment by kapware** [comment]
Just for reference, if someone stumbles here looking for similar looking error:
Error like `Uncaught Error: Undefined nameToPath for namespace.name` happened to me, when I moved cljs file to another directory, changed `require`, but forgot to actually rename the namespace definition.

**Comment by theronic** [comment]
As per @kapware, check that your `(ns my-project.app)` matches the folder structure, e.g. if located at `~/src/cljs/my-project/app.cljs`. Even a single character will cause this. This catches me all the time - I wish the compiler would warn me, or just not care. The whole concept of files for this seems broken to me. Which matters - namespaces or files? Either namespaces should be the true modular layout, or files - not both.
