### ISSUE TITLE
JSONp support

### ISSUE THREAD

**Issue by cpetzold** [r0man/cljs-http#30]
How do you feel about adding JSONp support? To do it right may mean changing the core interaction between `core/request` and `client/request`, but it might be nice to abstract away the communication layer a bit more. JSONp doesn't fit _that_ nicely with this library since requests can't be aborted, and all you get back is the response body -- but a lot of the middleware fns in client would still be useful.

Here's a first pass at the request fn:
```clojure
(defn jsonp-request
  "Behaves like request, using JSONP instead of XHR.
   JSONP requests can not be aborted."
  [request]
  (let [channel (async/chan)
        fn-name (gensym "jsonp")
        request-url (util/build-url
                            (update-in request [:query-string] str "&callback=" fn-name))
        script-element (js/document.createElement "script")]
    (.setAttribute script-element "src" request-url)
    (aset js/window fn-name
          (fn [body]
            (.removeChild js/document.head script-element)
            (doto channel
              (async/put! {:status 200
                           :success true
                           :body body})
              async/close!)))
    (.appendChild js/document.head script-element)
    channel))
```

I'm happy to put together a PR if you think it fits!

**Comment by shofetim** [comment]
:+1: JSON would be nice

**Comment by ducky427** [comment]
+1

**Comment by t3chnoboy** [comment]
:+1:

**Comment by mhjort** [comment]
+1 for JSONP

**Comment by r0man** [comment]
Ok, ok. :) Patch welcome!

**Comment by t3chnoboy** [comment]
>JSONp doesn't fit that nicely with this library since requests can't be aborted, and all you get back is the response body
@cpetzold  they can :smile:
see https://github.com/t3chnoboy/cljs-http/blob/jsonp/test/cljs_http/test/client.cljs#L148-L156
