### ISSUE TITLE
Aborting requests

### ISSUE THREAD

**Issue by Deraen** [r0man/cljs-http#39]
Hi,

I think there is a problem with the `cljs-http.core/abort!`. It tries to find the XhrRequest  by using the channel as map key, this is problematic as several wrappers are creating new channels using async/map. This means that the user doesn't have the original channel and `abort!` doesn't work.

Perhaps it would be possible to remove the need for `pending-requests` atom and add logic to `cljs-http.core/request` which would abort the request is channel is closed by the user?
- async/map would still be problematic as closing the output channel doesn't close input channels, but I think this could be solved

**Comment by decoursin** [comment]
For anyone who's looking to use this, it's actually `{:cancel cancel}` not `{:cancel-channel cancel}`. I only mention this because it seems to be the only documentation, besides the code itself.
