### ISSUE TITLE
Show all response headers

### ISSUE THREAD

**Issue by apsdehal** [r0man/cljs-http#58]
If I try to get `:headers` from the response, only header I get is content-type.

**Comment by r0man** [comment]
I think you might have a CORS problem. Did you try to set the access-control-allow-headers  on your server?

**Comment by r0man** [comment]
I think you might have a CORS problem. Did you try to set the access-control-allow-headers  on your server?

**Comment by r0man** [comment]
I think you might have a CORS problem. Did you try to set the access-control-allow-headers  on your server?

**Comment by r0man** [comment]
I think you might have a CORS problem. Did you try to set the access-control-allow-headers  on your server?

**Comment by apsdehal** [comment]
Yes. I have set the access-control-allow-headers on the server

**Comment by r0man** [comment]
Sorry, I meant this header: access-control-expose-headers

**Comment by apsdehal** [comment]
No we don't have that, if it is necessary how is network showing the response headers?

**Comment by r0man** [comment]
I have set them to `Access-Control-Expose-Headers: etag, link, x-total`

**Comment by apsdehal** [comment]
Thanks for the help, let me confirm this and I will close the issue.

**Comment by apsdehal** [comment]
Thanks issue is solved.

**Comment by geoffreymuchai** [comment]
I am experiencing problems retrieving the `etag` value from the response provided by the server. The server has been setup to expose the `etags` through the following configuration: 

`Access-Control-Expose-Headers: etag, link, x-total`. 

The only headers returned are `{last-modified Fri, 05 Jun 2015 07:45:53 GMT, content-language en, content-type application/json}`. The server has been configured to allow CORS requests to receive etag information but it still doesn't work.

Any ideas on how to resolve this will be greatly appreciated.
