### ISSUE TITLE
Support for nodejs

### ISSUE THREAD

**Issue by rukor** [r0man/cljs-http#59]
Is there planned support for cljs running under nodejs (in a server environment) ?

Thanks

**Comment by r0man** [comment]
No, noting planned. Patch welcome!

**Comment by rukor** [comment]
Thanks, I will take a look.

**Comment by moea** [comment]
Assuming the presence of the "xmlhttprequest" NPM package (e.g. via lein-npm), then this works fine: https://gist.github.com/moea/63d7a882e4ad333f3b5a

Performing that kind of global adjustment is obviously a less-good idea in a library intended for reuse.  If there was interest in including something similar, I think the lowest-impact approach would be to include an `xhr-factory` function, which takes in a function, and returns a class like the one linked above, with the input serving as the implementation of the `createInstance` method.  Additionally, requests could support something like a `:cljs-http/xhr-factory` key in request maps, which will pass the option to `XhrIo`. And/or a `(cljs-http.core/set-xhr-factory!)` function which sets the factory for all requests originating via cljs-http.  The code for a Node user would be something like:

```clojure
(require '[cljs.nodejs :as nodejs])
(require '[cljs-http.core :as http])

(def xhr (.-XMLHttpRequest (nodejs/require "xmlhttprequest"))

(http/set-xhr-factory! (http/xhr-factory #(xhr.)))

;; use library normally
```

Which isn't too bad, and doesn't require there to be anything vaguely Node-specific in cljs-http.

**Comment by vikeri** [comment]
I would find an implemented version of this very useful as well. HTTPS + Node + CLJS seems like a pretty common/powerful usecase?

**Comment by moea** [comment]
@vikeri Maybe this is helpful meanwhile https://github.com/nervous-systems/kvlt

**Comment by vikeri** [comment]
I managed to get it working. But `kvit` seems to be a great project! I'm starting to work with React Native so this possibly comes in handy there :)
