### ISSUE TITLE
Error when applying transducer on channel to map :body

### ISSUE THREAD

**Issue by tolgap** [r0man/cljs-http#83]
Hi, I'm using the example in the readme to always take `:body` out of my requests at the API call function:

```{clojure}
(defn json-to [path]
  (http/get path {:with-credentials? false
                  :channel (chan 1 (map :body))}))
```

But I get an error in my console: "Error: [object Object] is not ISeqable".
The request looks like this:

```
{"body": [
  {"id": 1},
  ...
  ]
}
```

Is there something extra I need to do? Seems like I can't actually `map` over my request because it's a Javascript object and not a cljs data type.

**Comment by decoursin** [comment]
You need this: `{:accepts :json ...}` in the options list.

**Comment by tolgap** [comment]
@decoursin thanks that solved it.
