### ISSUE TITLE
Enable to configure cljs-http.core/jsonp if response keys are keywordized

### ISSUE THREAD

**Issue by jindrichmynarz** [r0man/cljs-http#86]
I need `cljs-http.core/jsonp` not to keywordize response keys (<https://github.com/r0man/cljs-http/blob/master/src/cljs_http/core.cljs#L116>), because the keys in the JSON I'm requesting contain slashes and are thus (incorrectly) casted to namespaced keywords. Currently, keywordization is hard-coded, so it's not possible to disable it. Is it possible to add an option to configure if keys would be keywordized (defaulting to `true` to maintain compatibility)?

**Comment by r0man** [comment]
@jindrichmynarz Yes, patch with test welcome!

**Comment by jindrichmynarz** [comment]
I drafted a solution to this issue in #87, aiming for minimal changes to the library. Additional changes may include reducing the boilerplate in JSON-P tests, reusing `cljs-http.util/json-decode` in `cljs-http.core/jsonp`, and enabling to set `:keywordize-keys` there as well.
